DEFAULT_RESOLUTION_X = 800
DEFAULT_RESOLUTION_Y = 600

PIXELS_PER_UNIT = 96

# how many different rotations to cache per object
ROTATION_CACHE_RESOLUTION = 1000

PLAYER_SPEED = 3.0
PLAYER_ROTATION_SPEED = 5.0
PLAYER_JUMP_MAX_HEIGHT = 1.5
PLAYER_JUMP_TIME = 0.4
# 0 = a * t + v
# 0 = v^2 + 2 * a * h
# a = -v / t
# 0 = v^2 + -2vh/t
# 0 = v + -2h/t
# v = 2h/t
PLAYER_JUMP_VELOCITY = 2.0 * PLAYER_JUMP_MAX_HEIGHT / PLAYER_JUMP_TIME
PLAYER_JUMP_ACCELERATION = -PLAYER_JUMP_VELOCITY / PLAYER_JUMP_TIME
PLAYER_RUNNING_PERIOD = 250
